url: "https://c5a5-95-103-19-89.eu.ngrok.io"
apps:
  app1:
    clientID: 1-2-3-4
    clientSecret: secret
    issuer: "https://c5a5-95-103-19-89.eu.ngrok.io"
    redirectURIs: ["http://localhost:8081/callback", "https://openidconnect.net/callback", "http://localhost:8082/securityRealm/finishLogin"]
